/**
 * WeddingWithIndia - Centralized Single Source of Truth for Business Metrics & Key Performance Indicators.
 * All metrics across marketing pages, headers, footers, dashboards, and metadata MUST be imported from here.
 */

import { COMMISSION_MODEL, PRICING_TIERS, WEIGHTED_AVERAGE_BOOKING } from "./financial-model";

export const BUSINESS_METRICS = {
  WEDDINGS_HOSTED: "Awaiting first verified celebration",
  WEDDINGS_HOSTED_NUM: 0,
  GLOBAL_GUESTS: "Awaiting first verified guest",
  GLOBAL_GUESTS_NUM: 0,
  COUNTRIES_REPRESENTED: "Awaiting launch",
  COUNTRIES_REPRESENTED_NUM: 0,
  AVERAGE_RATING: "No verified reviews yet",
  AVERAGE_RATING_NUM: 0,
  AVERAGE_RATING_LABEL: "Awaiting reviews",
  SATISFACTION_RATE: "Awaiting launch",
  SATISFACTION_RATE_NUM: 0,
  PLATFORM_FEE_PERCENT: COMMISSION_MODEL.PLATFORM_COMMISSION_PERCENT, // 22%
  HOST_ALLOCATION_PERCENT: COMMISSION_MODEL.HOST_ALLOCATION_PERCENT, // 78%
  AGENT_COMMISSION_AVERAGE: COMMISSION_MODEL.AGENT_REFERRAL_PAYOUT_DEFAULT, // 1000
  HOST_REFERRAL_PERCENT: COMMISSION_MODEL.HOST_REFERRAL_COMMISSION_PERCENT, // 4%
  DEFAULT_CURRENCY: "INR",
  MIN_PRICE: PRICING_TIERS.BUDGET.priceINR, // ₹9,000
  MAX_PRICE: PRICING_TIERS.VIP.priceINR, // ₹30,000
  WEIGHTED_AVG_BOOKING_INR: WEIGHTED_AVERAGE_BOOKING.priceINR, // ₹15,500
  WOULD_RECOMMEND_PERCENT: 0,
  GUESTS_ATTENDED: "0",
} as const;

export type BusinessMetrics = typeof BUSINESS_METRICS;
