/**
 * WeddingWithIndia - Centralized Single Source of Truth for Business Metrics & Key Performance Indicators.
 * All metrics across marketing pages, headers, footers, dashboards, and metadata MUST be imported from here.
 */

import { COMMISSION_MODEL, PRICING_TIERS, WEIGHTED_AVERAGE_BOOKING } from "./financial-model";

export const BUSINESS_METRICS = {
  WEDDINGS_HOSTED: "1,400+",
  WEDDINGS_HOSTED_NUM: 1400,
  GLOBAL_GUESTS: "12,000+",
  GLOBAL_GUESTS_NUM: 12000,
  COUNTRIES_REPRESENTED: "80+",
  COUNTRIES_REPRESENTED_NUM: 80,
  AVERAGE_RATING: "4.96",
  AVERAGE_RATING_NUM: 4.96,
  AVERAGE_RATING_LABEL: "4.96/5",
  SATISFACTION_RATE: "98%",
  SATISFACTION_RATE_NUM: 98,
  PLATFORM_FEE_PERCENT: COMMISSION_MODEL.PLATFORM_COMMISSION_PERCENT, // 28%
  HOST_ALLOCATION_PERCENT: COMMISSION_MODEL.HOST_ALLOCATION_PERCENT, // 72%
  AGENT_COMMISSION_PERCENT: COMMISSION_MODEL.AGENT_REFERRAL_COMMISSION_PERCENT, // 7%
  HOST_REFERRAL_PERCENT: COMMISSION_MODEL.HOST_REFERRAL_COMMISSION_PERCENT, // 4%
  DEFAULT_CURRENCY: "INR",
  MIN_PRICE: PRICING_TIERS.CULTURAL_GUEST.priceINR, // ₹7,499
  MAX_PRICE: PRICING_TIERS.PREMIUM_HOSTED.priceINR, // ₹29,999
  WEIGHTED_AVG_BOOKING_INR: WEIGHTED_AVERAGE_BOOKING.priceINR, // ₹13,799
  WOULD_RECOMMEND_PERCENT: 98,
  GUESTS_ATTENDED: "12,000+",
} as const;

export type BusinessMetrics = typeof BUSINESS_METRICS;
