import type {
  Wedding,
  Category,
  Testimonial,
  Country,
  FAQItem,
  Stat,
  HowItWorksStep,
} from "@/types";

export const featuredWeddings: Wedding[] = [
  {
    id: "w1",
    slug: "grand-maharaja-wedding",
    title: "The Grand Maharaja Wedding",
    location: "Umaid Bhawan Palace, Jodhpur, Rajasthan",
    city: "Jodhpur",
    state: "Rajasthan",
    country: "India",
    countryCode: "IN",
    category: "Royal",
    pricePerGuest: 17999,
    currency: "USD",
    rating: 5.0,
    reviewCount: 14,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1615966650071-855b15f29ad1?w=400&q=80",
    coupleName: "Devika & Kaber Singhania",
    hostName: "Devika & Kaber Singhania",
    hostAvatar: "https://images.unsplash.com/photo-1615966650071-855b15f29ad1?w=400&q=80",
    featured: true, sponsored: true, isDemo: true,
    tags: ["Palace", "Royal Heritage", "Umaid Bhawan", "Baraat Procession", "Fine Dining"],
    date: "2026-11-18",
    religion: "Hindu (Rajput Tradition)",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 3,
    languages: ["English", "Hindi", "Marwari"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Sponsored",
    gallery: ["https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=80"],
    story: "Experience royal Marwari grandeur at Umaid Bhawan Palace, Jodhpur. Enjoy authentic Sangeet performances, sacred Phera rituals, and a royal procession through the Blue City.",
    coupleBio: "The Singhania family welcomes global travelers to experience royal Marwari hospitality and centuries-old wedding traditions.",
    timeline: [],
    traditions: [],
    dressCode: "Festive Indian Royal Attire / Black Tie",
    foodDescription: "Royal MarwariThali featuring Dal Baati Churma and saffron sweets.",
    venueDescription: "Umaid Bhawan Palace, Jodhpur.",
    accommodation: "Heritage Palace Pavilion Suite.",
    included: ["Access to ceremonies", "Feasts & beverages"],
    notIncluded: ["Flights", "Hotel stay"],
    reviews: [],
    faqs: [],
  },
  {
    id: "w23",
    slug: "shimla-himalayan-pine-royal-wedding",
    title: "Shimla Himalayan Pine Forest Royal Celebration",
    location: "Wildflower Hall, An Oberoi Resort, Shimla, Himachal Pradesh",
    city: "Shimla",
    state: "Himachal Pradesh",
    country: "India",
    countryCode: "IN",
    category: "Royal",
    pricePerGuest: 16999,
    currency: "USD",
    rating: 5.0,
    reviewCount: 9,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1640953148126-1962ec17a92b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    coupleImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coupleName: "Vikramaditya & Gayatri Himachal",
    hostName: "Vikramaditya & Gayatri Himachal",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    featured: true, sponsored: true, isDemo: true,
    tags: ["Pine Forest", "Himalayan Luxury", "Wildflower Hall", "Pahadi Royal", "Oberoi Estate"],
    date: "2028-05-18",
    religion: "Hindu (Himachali Rajput Tradition)",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 3,
    languages: ["English", "Hindi", "Pahadi"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Sponsored",
    gallery: ["https://images.unsplash.com/photo-1640953148126-1962ec17a92b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
    story: "Experience mountain luxury at Wildflower Hall, Shimla. Enjoy authentic Pahadi Dham feasts, cedar forest pheras, and Sitar melodies overlooking Himalayan peaks.",
    coupleBio: "Vikramaditya & Gayatri invite global guests to experience serene Himachali royal hospitality.",
    timeline: [],
    traditions: [],
    dressCode: "Festive Velvet Sherwani / Silk Dhatu Saree",
    foodDescription: "Traditional Himachali Dham feast cooked by master Botis.",
    venueDescription: "Wildflower Hall, An Oberoi Resort, Shimla.",
    accommodation: "Himalayan Forest View Luxury Suite.",
    included: ["Access to ceremonies", "Feasts & beverages"],
    notIncluded: ["Flights", "Hotel stay"],
    reviews: [],
    faqs: [],
  },
  {
    id: "w2",
    slug: "lakeside-rajput-celebration",
    title: "Lakeside Rajput Celebration",
    location: "Jagmandir Island Palace, Udaipur, Rajasthan",
    city: "Udaipur",
    state: "Rajasthan",
    country: "India",
    countryCode: "IN",
    category: "Royal",
    pricePerGuest: 14999,
    currency: "USD",
    rating: 4.95,
    reviewCount: 11,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coupleName: "Aditya & Sanjana Rathore",
    hostName: "Aditya & Sanjana Rathore",
    hostAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    featured: true, sponsored: false, isDemo: true,
    tags: ["Lake Pichola", "Sunset Boat", "Shehnai", "Royal Mewari"],
    date: "2026-12-04",
    religion: "Hindu (Mewari Rajput)",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 3,
    languages: ["English", "Hindi", "Rajasthani"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: ["https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=80"],
    story: "A romantic wedding on Lake Pichola, Udaipur featuring sunset boat processions, classical shehnai recitals, and lakeside fine dining under the stars.",
    coupleBio: "Aditya & Sanjana welcome global guests to share in centuries-old royal Mewari hospitality.",
    timeline: [],
    traditions: [],
    dressCode: "Traditional Elegant Ethnic",
    foodDescription: "Royal Mewari Thali.",
    venueDescription: "Jagmandir Island Palace.",
    accommodation: "Lakeside hotel.",
    included: ["Access to ceremonies", "Feasts"],
    notIncluded: ["Flights"],
    reviews: [],
    faqs: [],
  },
  {
    id: "w3",
    slug: "kerala-backwater-matrimony",
    title: "Kerala Backwater Matrimony",
    location: "Kumarakom Lake Resort, Alleppey, Kerala",
    city: "Alleppey",
    state: "Kerala",
    country: "India",
    countryCode: "IN",
    category: "Nature",
    pricePerGuest: 11499,
    currency: "USD",
    rating: 4.9,
    reviewCount: 9,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coupleName: "Karan & Meera Nambiar",
    hostName: "Karan & Meera Nambiar",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    featured: false, sponsored: false, isDemo: true,
    tags: ["Backwaters", "Banana Leaf Sadya", "Kathakali", "Coconut Grove"],
    date: "2027-01-14",
    religion: "Hindu (Malayali)",
    luxuryLevel: "Luxury",
    durationDays: 2,
    languages: ["English", "Malayalam"],
    isVerified: true,
    isCurated: false,
    gallery: ["https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200&q=80"],
    story: "Serene backwater matrimony amidst palm groves in Alleppey. Features traditional Kerala Sadya on banana leaves and Kathakali cultural performances.",
    coupleBio: "Karan & Meera welcome guests to coastal Kerala hospitality.",
    timeline: [],
    traditions: [],
    dressCode: "Kasavu Saree / Cream Mundu",
    foodDescription: "24-item traditional vegetarian Sadya.",
    venueDescription: "Kumarakom Lake Resort.",
    accommodation: "Waterfront resort.",
    included: ["Sadya feast", "Cultural performances"],
    notIncluded: ["Flights"],
    reviews: [],
    faqs: [],
  },
  {
    id: "w4",
    slug: "goan-sunset-beach-wedding",
    title: "Goan Sunset Beach Nuptials",
    location: "Riva Beach Resort, Mandrem, Goa",
    city: "Mandrem",
    state: "Goa",
    country: "India",
    countryCode: "IN",
    category: "Beach",
    pricePerGuest: 12999,
    currency: "USD",
    rating: 4.88,
    reviewCount: 12,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    coupleName: "Rohan & Alisha D'Souza",
    hostName: "Rohan & Alisha D'Souza",
    hostAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    featured: true, sponsored: false, isDemo: true,
    tags: ["Beachfront", "Sundowner", "Goan Seafood", "Mandap"],
    date: "2027-02-12",
    religion: "Interfaith",
    luxuryLevel: "Luxury",
    durationDays: 2,
    languages: ["English", "Konkani", "Hindi"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: ["https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80"],
    story: "A vibrant beachfront celebration on Mandrem Beach with sunset ocean views, live Goan brass music, fresh seafood banquets, and floral mandap ceremonies.",
    coupleBio: "Rohan & Alisha celebrate coastal Goan warmth and hospitality.",
    timeline: [],
    traditions: [],
    dressCode: "Beach Formal / Pastel Linen",
    foodDescription: "Fresh Goan seafood & tropical fruit buffet.",
    venueDescription: "Riva Beach Resort.",
    accommodation: "Beachfront resort.",
    included: ["Beach ceremony", "Gala dinner"],
    notIncluded: ["Flights"],
    reviews: [],
    faqs: [],
  },
  {
    id: "w5",
    slug: "varanasi-ganges-spiritual-union",
    title: "Varanasi Ganges Spiritual Union",
    location: "BrijRama Palace, Darbhanga Ghat, Varanasi, Uttar Pradesh",
    city: "Varanasi",
    state: "Uttar Pradesh",
    country: "India",
    countryCode: "IN",
    category: "Traditional",
    pricePerGuest: 10999,
    currency: "USD",
    rating: 4.97,
    reviewCount: 15,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1544124499-58912cbddaad?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    coupleName: "Shivam & Priya Tripathi",
    hostName: "Shivam & Priya Tripathi",
    hostAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    featured: false, sponsored: false, isDemo: true,
    tags: ["Ganges", "Ghat Aarti", "Vedic Chants", "Heritage Palace"],
    date: "2027-03-05",
    religion: "Hindu (Vedic)",
    luxuryLevel: "Luxury",
    durationDays: 2,
    languages: ["English", "Hindi", "Sanskrit"],
    isVerified: true,
    isCurated: false,
    gallery: ["https://images.unsplash.com/photo-1544124499-58912cbddaad?w=1200&q=80"],
    story: "A sacred heritage wedding overlooking the holy Ganges River at Darbhanga Ghat. Features private Ganga Aarti, classical sitar recitals, and traditional Vedic chants.",
    coupleBio: "Shivam & Priya welcome guests to experience spiritual Varanasi tradition.",
    timeline: [],
    traditions: [],
    dressCode: "Traditional Banarasi Silk",
    foodDescription: "Sattvic Banarasi vegetarian thali.",
    venueDescription: "BrijRama Palace.",
    accommodation: "Heritage riverfront hotel.",
    included: ["Ganga Aarti boat transfer", "Banquets"],
    notIncluded: ["Flights"],
    reviews: [],
    faqs: [],
  },
  {
    id: "w6",
    slug: "punjabi-amritsar-golden-wedding",
    title: "Amritsar Golden Temple Wedding",
    location: "Welcomhotel by ITC Hotels, Amritsar, Punjab",
    city: "Amritsar",
    state: "Punjab",
    country: "India",
    countryCode: "IN",
    category: "Traditional",
    pricePerGuest: 13999,
    currency: "USD",
    rating: 4.93,
    reviewCount: 8,
    guestsAllowed: 0,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&q=80",
    coupleName: "Gurpreet & Harleen Dhillon",
    hostName: "Gurpreet & Harleen Dhillon",
    hostAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&q=80",
    featured: false, sponsored: false, isDemo: true,
    tags: ["Anand Karaj", "Bhangra", "Langar", "Golden Temple"],
    date: "2027-04-12",
    religion: "Sikh",
    luxuryLevel: "Luxury",
    durationDays: 3,
    languages: ["English", "Punjabi", "Hindi"],
    isVerified: true,
    isCurated: false,
    gallery: ["https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=1200&q=80"],
    story: "High-energy Punjabi wedding starting with sacred Anand Karaj near the Golden Temple, followed by Dhol drumming, Bhangra dances, and authentic Punjabi feasts.",
    coupleBio: "Gurpreet & Harleen invite global guests to vibrant Punjabi warmth.",
    timeline: [],
    traditions: [],
    dressCode: "Punjabi Kurta Pajama / Turban / Salwar Kameez",
    foodDescription: "Authentic Punjabi Butter Chicken & Paneer Tikka feast.",
    venueDescription: "Welcomhotel Amritsar.",
    accommodation: "Luxury city hotel.",
    included: ["Ceremony entry", "Feasts & Dhol performances"],
    notIncluded: ["Flights"],
    reviews: [],
    faqs: [],
  },
];

export const categories: Category[] = [
  {
    id: "royal",
    name: "Royal",
    slug: "royal",
    count: 6,
    weddingCount: 6,
    icon: "Crown",
    description: "Grand palaces, regal traditions & Maharaja heritage",
    imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80",
  },
  {
    id: "punjabi",
    name: "Punjabi",
    slug: "punjabi",
    count: 1,
    weddingCount: 1,
    icon: "Flame",
    description: "Vibrant celebrations full of joy, dhol & bhangra",
    imageUrl: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=800&q=80",
  },
  {
    id: "south-indian",
    name: "South Indian",
    slug: "south-indian",
    count: 2,
    weddingCount: 2,
    icon: "Flower2",
    description: "Sacred traditions with temple elegance & banana leaf sadyas",
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
  },
  {
    id: "beach",
    name: "Beach",
    slug: "beach",
    count: 3,
    weddingCount: 3,
    icon: "Waves",
    description: "Ocean-side romance at sunset along coastal shores",
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
  },
  {
    id: "destination",
    name: "Destination",
    slug: "destination",
    count: 6,
    weddingCount: 6,
    icon: "Compass",
    description: "Exotic locales from Himalayan peaks to tea estates",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: "traditional",
    name: "Traditional",
    slug: "traditional",
    count: 5,
    weddingCount: 5,
    icon: "Sparkles",
    description: "Time-honoured rituals, spiritual unions & rich heritage",
    imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
  },
];

export const weddingCategories = categories;

export const stats: Stat[] = [
  { label: "Curated Experiences", value: "22+" },
  { label: "Partner Cities", value: "18" },
  { label: "Guest Satisfaction", value: "99.4%" },
  { label: "Verified Hosts", value: "100%" },
];

export const heroStats = stats;

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Jenkins",
    role: "Cultural Enthusiast",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    content: "Attending Devika & Kaber's wedding in Udaipur was the most unforgettable cultural experience of my life. The hospitality of the Singhania family made us feel like lifelong friends.",
    rating: 5,
    location: "London, UK",
    weddingType: "Royal Rajput Wedding",
    date: "November 2025",
  },
  {
    id: "t2",
    name: "Marcus Vance",
    role: "Photographer & Traveler",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    content: "The colors, music, and traditions were breathtaking. WeddingWithIndia provided seamless coordination, clear dress code guidance, and an absolute VIP cultural pass.",
    rating: 5,
    location: "Sydney, Australia",
    weddingType: "Goan Sunset Beach Nuptials",
    date: "February 2026",
  },
];

export const countries: Country[] = [
  {
    code: "RJ",
    name: "Rajasthan",
    weddingCount: 5,
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
    description: "Royal palaces, golden desert dunes, and grand haveli celebrations in Udaipur, Jaipur & Jodhpur.",
  },
  {
    code: "GA",
    name: "Goa",
    weddingCount: 2,
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    description: "Sun-kissed beach nuptials, oceanfront mandaps, and tropical sunset receptions.",
  },
  {
    code: "KL",
    name: "Kerala",
    weddingCount: 3,
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    description: "Serene backwater houseboat processions, banana leaf Sadya feasts, and palm-shaded rituals.",
  },
  {
    code: "PB",
    name: "Punjab",
    weddingCount: 1,
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    description: "Vibrant Anand Karaj ceremonies, Golden Temple heritage, and high-energy Dhol bhangra.",
  },
  {
    code: "JK",
    name: "Kashmir & Ladakh",
    weddingCount: 2,
    imageUrl: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80",
    description: "Majestic Himalayan mountain views, Dal Lake luxury houseboats, and ancient monastery blessings.",
  },
  {
    code: "SI",
    name: "South India & Heritage",
    weddingCount: 9,
    imageUrl: "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&q=80",
    description: "Temple architecture, French Quarter villas in Pondicherry, Nizam palaces, and Coorg coffee estates.",
  },
];

export const faqItems: FAQItem[] = [
  {
    id: "f1",
    question: "What is WeddingWithIndia?",
    answer: "WeddingWithIndia is a premier cultural platform connecting international travelers and cultural enthusiasts with real Indian families hosting authentic wedding celebrations across India.",
    category: "General",
  },
  {
    id: "f2",
    question: "How are hosts and weddings verified?",
    answer: "Every wedding host undergoes strict identity verification, profile screening, and venue confirmation before listing their celebration.",
    category: "Verification",
  },
  {
    id: "f3",
    question: "What is included with a Guest Pass?",
    answer: "A Guest Pass includes access to scheduled ceremonial events, authentic wedding feasts, cultural performances, and assigned wedding buddy support.",
    category: "Experience",
  },
];

export const howItWorksSteps: HowItWorksStep[] = [
  {
    step: 1,
    icon: "Compass",
    title: "Browse Curated Celebrations",
    description: "Explore 22+ authentic Indian wedding experiences across Rajasthan, Goa, Kerala, and Punjab.",
  },
  {
    step: 2,
    icon: "UserCheck",
    title: "Request Host Approval",
    description: "Submit your guest profile for host review and receive personalized event details upon verification.",
  },
  {
    step: 3,
    icon: "PlaneTakeoff",
    title: "Prepare & Travel Support",
    description: "Your dedicated guest liaison assists with airport pickup, hotel coordination, and traditional attire guidance.",
  },
  {
    step: 4,
    icon: "Sparkles",
    title: "Attend as an Honoured Guest",
    description: "Receive your digital VIP Guest Pass, step inside sacred rituals, feast, dance, and celebrate as family.",
  },
];

