import type {
  Wedding,
  Category,
  Testimonial,
  Country,
  FAQItem,
  Stat,
  HowItWorksStep,
} from "@/types";

export const featuredWeddings: Wedding[] = [
  {
    id: "curated-1",
    slug: "royal-maharaja-palace-wedding-udaipur",
    title: "Royal Maharaja Palace Wedding",
    location: "Jagmandir Island Palace, Lake Pichola, Udaipur",
    city: "Udaipur",
    state: "Rajasthan",
    country: "India",
    countryCode: "IN",
    category: "Royal",
    pricePerGuest: 650,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    guestsAllowed: 30,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=85",
    coupleImage: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=85",
    coupleName: "Vikramaditya & Ananya Singh Rathore",
    hostName: "Rathore Royal Family of Mewar",
    hostAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=85",
    featured: true,
    tags: ["Palace", "Royal Heritage", "Lake Pichola", "Baraat Procession", "Fine Dining"],
    date: "2026-11-18",
    religion: "Hindu (Rajput Tradition)",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 3,
    languages: ["English", "Hindi", "Rajasthani"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Verified Showcase",
    gallery: [
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=85",
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=85",
      "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=85",
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=85",
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&q=85",
    ],
    story:
      "Join the royal Rathore family on Lake Pichola for a 3-day imperial Rajput wedding celebration. Experience majestic elephant baraat processions, traditional Shekhawati folk performances, royal banquets crafted by heritage chefs, and sacred Vedic pheras under the stars at Jagmandir Island Palace.",
    coupleBio:
      "Vikramaditya belongs to the royal lineage of Mewar and is a heritage hotelier. Ananya is a classical Kathak dancer and art historian. Together, they welcome international guests to share in centuries-old royal hospitality.",
    timeline: [
      {
        title: "Day 1: Royal Mehendi & Welcoming Feast",
        time: "16:00 - 22:00",
        date: "2026-11-18",
        description: "Arrival boat transfer across Lake Pichola. Henna artists, Marwari folk music, and a palace courtyard buffet.",
        icon: "Flower2",
      },
      {
        title: "Day 2: Sangeet & Musical Extravaganza",
        time: "19:00 - 01:00",
        date: "2026-11-19",
        description: "Ghoomar dance performances, royal fireworks over the lake, and a multi-course Rajasthani royal feast.",
        icon: "Sparkles",
      },
      {
        title: "Day 3: Grand Royal Baraat & Pheras",
        time: "17:00 - 23:30",
        date: "2026-11-20",
        description: "Majestic Baraat arrival on boat, traditional Vedic phere around the sacred fire, and royal farewell reception.",
        icon: "Crown",
      },
    ],
    traditions: [
      {
        title: "Ghoomar Folk Dance",
        description: "Traditional Rajasthani dance performed by women wearing vibrant ghagras.",
      },
      {
        title: "Royal Baraat Procession",
        description: "Groom's grand arrival accompanied by royal brass band, drums, and lighted lanterns.",
      },
      {
        title: "Vedic Saptapadi",
        description: "The seven sacred vows taken around the agni (sacred fire) invoking eternal harmony.",
      },
    ],
    dressCode: "Day 1: Vibrant Indo-Western / Kurta or Pastel Lehenga; Day 2: Royal Gold & Velvet Sangeet Attire; Day 3: Traditional Bandhgala or Royal Sherwani / Silk Sari.",
    theme: "Royal Imperial Gold & Crimson Palace Romance",
    ethnicity: "Rajput Marwari Culture",
    requiredGuests: 1,
    foodDescription: "Royal MewariThali featuring Dal Baati Churma, Laal Maas (optional gourmet vegetarian alternatives), Ker Sangri, saffron sweets, and artisanal mocktails.",
    venueDescription: "Jagmandir Island Palace surrounded by the serene waters of Lake Pichola with views of the City Palace.",
    accommodation: "Heritage Palace Pavilion Suite recommendation provided upon reservation confirmation.",
    included: [
      "Access to all 3 days of ceremonial festivities & royal feasts",
      "Private boat transfers across Lake Pichola for all events",
      "Dedicated English-speaking cultural concierge liaison",
      "Traditional welcome turban (Safa) or dupatta draping",
      "Custom henna application by royal mehndi artists",
      "All gourmet meals, royal banquets & refreshments",
    ],
    notIncluded: [
      "International airfare to Udaipur (UDR)",
      "Hotel accommodation costs",
      "Personal shopping & local transit outside wedding events",
    ],
    reviews: [],
    faqs: [
      {
        id: "faq-curated-1",
        question: "Will I have a dedicated liaison to guide me through rituals?",
        answer: "Yes! Every guest is paired with a dedicated English-speaking cultural liaison who guides you through ceremony dress etiquette, ritual meanings, and photo opportunities.",
        category: "Guest Experience",
      },
      {
        id: "faq-curated-2",
        question: "What is the dress code assistance?",
        answer: "Our concierge team connects you with Udaipur's premier royal attire boutiques for custom fitting upon arrival, or provides a detailed attire guide prior to travel.",
        category: "Attire & Culture",
      },
    ],
  },
  {
    id: "curated-2",
    slug: "goa-sunset-beachfront-wedding",
    title: "Goa Sunset Beachfront Wedding",
    location: "Riva Beach Resort, Mandrem Beach, South Goa",
    city: "Goa",
    state: "Goa",
    country: "India",
    countryCode: "IN",
    category: "Beach",
    pricePerGuest: 450,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    guestsAllowed: 25,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=85",
    coupleImage: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=600&q=85",
    coupleName: "Rohan & Natasha Fernandes",
    hostName: "Fernandes Family of Goa",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85",
    featured: true,
    tags: ["Beachfront", "Ocean Sunset", "Seafood Feast", "Live Band", "Tropical Romance"],
    date: "2026-12-10",
    religion: "Interfaith (Catholic & Hindu fusion)",
    luxuryLevel: "Luxury",
    durationDays: 2,
    languages: ["English", "Konkani", "Hindi"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Handpicked Experience",
    gallery: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=85",
      "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=85",
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=85",
    ],
    story:
      "Celebrate under sway palm trees and ocean breezes at Mandrem Beach. Experience a vibrant blend of Goan Catholic warmth and Hindu wedding vibrance with live brass bands, fresh coastal seafood banquets, barefoot beach cocktail parties, and romantic sunset vows.",
    coupleBio:
      "Rohan is an architect from Panaji and Natasha is a marine biologist. Their wedding celebrates Goan heritage, coastal warmth, and environmental sustainability.",
    timeline: [
      {
        title: "Day 1: Sunset Sundowner & Haldi Pool Party",
        time: "15:30 - 21:00",
        date: "2026-12-10",
        description: "Yellow attire Haldi by the beach pool, live saxophone, fresh coconut cocktails, and Goan feni tasting.",
        icon: "Waves",
      },
      {
        title: "Day 2: Beachfront Sunset Ceremony & Gala Dinner",
        time: "16:30 - 23:30",
        date: "2026-12-11",
        description: "Oceanfront floral mandap ceremony at sunset followed by live Goan band performance and seafood extravaganza.",
        icon: "Sparkles",
      },
    ],
    traditions: [
      {
        title: "Roce Ceremony",
        description: "Goan coconut milk blessing ceremony wishing prosperity and radiant skin to the couple.",
      },
      {
        title: "Sunset Mandap Vows",
        description: "Floral canopy vows with the Arabian Sea as the backdrop.",
      },
    ],
    dressCode: "Day 1: Tropical Yellow / Linen Resort Wear; Day 2: Elegant Pastel Beach Formal / Flowy Silk Dress.",
    theme: "Tropical Ocean Sunset & White Orchid Elegance",
    foodDescription: "Goan Fish Curry, Prawn Balchão, Vegetable Caldine, Bebinca dessert, and fresh tropical fruit bar.",
    venueDescription: "Private beachfront lawn overlooking the Arabian Sea with private coconut grove pathways.",
    accommodation: "Beachfront villa recommendation list provided upon booking confirmation.",
    included: [
      "Access to 2 days of beachfront events & oceanside feasts",
      "Unlimited coastal buffet, sea food bar & signature cocktails",
      "On-site concierge escort & cultural orientation",
      "Goan floral garland welcome",
    ],
    notIncluded: [
      "Travel to Goa International Airport (GOI / GOX)",
      "Hotel stay costs",
    ],
    reviews: [],
    faqs: [
      {
        id: "faq-curated-2-1",
        question: "Is vegetarian and vegan food available at the beach feast?",
        answer: "Absolutely! The chef prepares dedicated authentic Goan vegetarian and vegan curries alongside coastal seafood options.",
        category: "Food & Dining",
      },
    ],
  },
  {
    id: "curated-3",
    slug: "rajasthani-fort-heritage-celebration-jaipur",
    title: "Rajasthani Fort Heritage Celebration",
    location: "Chomu Palace Fort, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    countryCode: "IN",
    category: "Royal",
    pricePerGuest: 580,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    guestsAllowed: 35,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=85",
    coupleImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=85",
    coupleName: "Aditya & Rajeshwari Shekhawat",
    hostName: "Shekhawat Heritage Family",
    hostAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=85",
    featured: true,
    tags: ["Heritage Fort", "Jaipur Palace", "Royal Procession", "Marwari Feast", "Folk Music"],
    date: "2026-11-25",
    religion: "Hindu (Traditional Rajput)",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 3,
    languages: ["English", "Hindi", "Marwari"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Verified Showcase",
    gallery: [
      "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=85",
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=85",
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=85",
    ],
    story:
      "Experience a 300-year-old fort wedding in Pink City Jaipur. Featuring camel processions, royal turban tying, puppet theatre, intricate mehendi artistry, and royal courtyard dining under illuminated palace arches.",
    coupleBio:
      "Aditya is a Jaipur royal heritage restorer and Rajeshwari is a fashion designer specializing in royal Zardosi embroidery.",
    timeline: [
      {
        title: "Day 1: Fort Mehendi & Puppet Carnival",
        time: "14:00 - 20:00",
        date: "2026-11-25",
        description: "Camel rides, Marwari puppet shows, royal henna, and traditional street food bazaar.",
        icon: "Compass",
      },
      {
        title: "Day 2: Royal Sangeet Night",
        time: "19:00 - 00:30",
        date: "2026-11-26",
        description: "Choreographed family dance, live Sufi music ensemble, and royal Mughlai-Rajasthani banquet.",
        icon: "Sparkles",
      },
      {
        title: "Day 3: Palace Baraat & Sacred Pheras",
        time: "16:00 - 23:00",
        date: "2026-11-27",
        description: "Royal vintage car & horse procession, Vedic mandap pheras, and fireworks finale.",
        icon: "Crown",
      },
    ],
    traditions: [
      {
        title: "Safa Tying",
        description: "Traditional royal Rajasthani turban tying ritual for all male guests.",
      },
      {
        title: "Langa Manganiyar Folk Performance",
        description: "World-renowned desert folk musicians performing soul-stirring heritage melodies.",
      },
    ],
    dressCode: "Day 1: Bright Pink / Yellow Ethnic Wear; Day 2: Royal Velvet / Embroidered Kurta; Day 3: Traditional Rajput Royal Dress.",
    foodDescription: "Authentic Rajasthani Royal Thali: Gatte ki Sabzi, Churma, Laal Maas, Ghevar sweets, and saffron lassi.",
    venueDescription: "Chomu Palace Fort with 300-year-old carved marble courtyards and intricate frescoed halls.",
    accommodation: "Fort heritage room booking guide provided upon reservation.",
    included: [
      "3 Days of full event admission & palace banquets",
      "Royal Safa (turban) and dupatta styling for guests",
      "English-speaking cultural liaison & photowalk guide",
    ],
    notIncluded: ["Flight to Jaipur (JAI)", "Personal hotel stay"],
    reviews: [],
    faqs: [],
  },
  {
    id: "curated-4",
    slug: "kerala-sacred-temple-backwater-ceremony",
    title: "Kerala Sacred Temple & Backwater Ceremony",
    location: "Kumarakom Lake Resort, Vembanad Lake, Kerala",
    city: "Kochi",
    state: "Kerala",
    country: "India",
    countryCode: "IN",
    category: "South Indian",
    pricePerGuest: 380,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    guestsAllowed: 20,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=1200&q=85",
    coupleImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=85",
    coupleName: "Arjun & Lakshmi Nambiar",
    hostName: "Nambiar Heritage Family of Travancore",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85",
    featured: true,
    tags: ["Temple Wedding", "Backwater Houseboat", "Traditional Sadhya", "Chenda Melam", "Kerala Silk"],
    date: "2026-11-30",
    religion: "Hindu (Kerala Brahmin Rituals)",
    luxuryLevel: "Luxury",
    durationDays: 2,
    languages: ["English", "Malayalam", "Tamil"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Handpicked Experience",
    gallery: [
      "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=1200&q=85",
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=85",
    ],
    story:
      "Experience God's Own Country in peaceful splendour. A 2-day traditional South Indian wedding featuring morning temple rituals, Chenda Melam drum ensembles, lotus flower mandaps, backwater houseboat cruises, and authentic 24-dish Sadhya feasts served on fresh banana leaves.",
    coupleBio:
      "Arjun is an Ayurveda physician and Lakshmi is an classical Mohiniyattam dancer. They invite global guests to witness Kerala's serene temple heritage.",
    timeline: [
      {
        title: "Day 1: Houseboat Welcome & Evening Kathakali Performance",
        time: "15:00 - 20:30",
        date: "2026-11-30",
        description: "Backwater sunset cruise on traditional Kerala houseboats, Kathakali dance drama, and coconut seafood feast.",
        icon: "Waves",
      },
      {
        title: "Day 2: Morning Temple Kalyanam & Royal Sadhya Feast",
        time: "08:30 - 15:00",
        date: "2026-12-01",
        description: "Sacred morning Muhurtham ceremony with Chenda Melam percussion, followed by 24-course banana leaf Sadhya feast.",
        icon: "Flame",
      },
    ],
    traditions: [
      {
        title: "Chenda Melam Ensembles",
        description: "Thrilling traditional Kerala percussion ensemble performed by 15 master drummers.",
      },
      {
        title: "Traditional Ela Sadhya",
        description: "Sacred vegetarian feast of 24 dishes served on fresh banana leaves.",
      },
    ],
    dressCode: "Day 1: Comfortable Linen / Kurta; Day 2: Kasavu Gold-bordered Kerala Sari or Mundu / White Shirt.",
    foodDescription: "24-item traditional Sadhya: Avial, Thoran, Payasam, Parippu, Appam with Stew, and fresh coconut water.",
    venueDescription: "Serene lakeside garden at Vembanad Lake backwaters surrounded by lotus ponds.",
    accommodation: "Lakeside villa recommendation list provided.",
    included: [
      "2 Days event access & backwater houseboat cruise",
      "Authentic 24-course banana leaf Sadhya feast",
      "Traditional Kerala Kasavu garment welcome gift",
      "Cultural liaison support",
    ],
    notIncluded: ["Flight to Cochin (COK)", "Hotel stay"],
    reviews: [],
    faqs: [],
  },
  {
    id: "curated-5",
    slug: "punjabi-big-fat-wedding-amritsar",
    title: "Punjabi Big Fat Wedding & Bhangra Night",
    location: "Fort Gobindgarh, Amritsar",
    city: "Amritsar",
    state: "Punjab",
    country: "India",
    countryCode: "IN",
    category: "Punjabi",
    pricePerGuest: 490,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    guestsAllowed: 30,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&q=85",
    coupleImage: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=85",
    coupleName: "Gurpreet & Harleen Dhillon",
    hostName: "Dhillon Family of Amritsar",
    hostAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=85",
    featured: true,
    tags: ["Punjabi Wedding", "Bhangra Dhol", "Grand Feast", "Golden Temple Visit", "Heritage Fort"],
    date: "2026-12-05",
    religion: "Sikh (Anand Karaj Tradition)",
    luxuryLevel: "Luxury",
    durationDays: 3,
    languages: ["English", "Punjabi", "Hindi"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Verified Showcase",
    gallery: [
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&q=85",
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=85",
    ],
    story:
      "Get ready for unparalleled energy, joy, and hospitality! A 3-day Punjabi celebration at historic Fort Gobindgarh in Amritsar. High-energy dhol drumming, midnight Bhangra competitions, tandoori food feasts, and peaceful morning Anand Karaj blessings.",
    coupleBio:
      "Gurpreet is an organic farmer & entrepreneur and Harleen is a university professor. They look forward to welcoming global guests into their energetic Punjabi family circle.",
    timeline: [
      {
        title: "Day 1: Sangeet & Midnight Dhol Night",
        time: "18:00 - 02:00",
        date: "2026-12-05",
        description: "Live Dhol drummers, Bhangra workshop for guests, tandoori live counters, and open bar.",
        icon: "Sparkles",
      },
      {
        title: "Day 2: Morning Anand Karaj & Royal Reception",
        time: "09:30 - 23:00",
        date: "2026-12-06",
        description: "Sacred Gurdwara Anand Karaj wedding ceremony followed by grand fort banquet reception.",
        icon: "Crown",
      },
    ],
    traditions: [
      {
        title: "Anand Karaj",
        description: "The blissful Sikh wedding ceremony centered around the Guru Granth Sahib.",
      },
      {
        title: "Dhol & Bhangra Dance Off",
        description: "High-octane Punjabi folk dance celebration.",
      },
    ],
    dressCode: "Day 1: Vibrant Magenta / Orange Party Wear; Day 2: Elegant Sherwani / Lehenga with head covering for Gurdwara.",
    foodDescription: "Amritsari Kulcha, Butter Chicken, Dal Makhani, Sarson ka Saag, Tandoori paneer, and hot jalebis.",
    venueDescription: "Fort Gobindgarh historic ramparts illuminated with fairy lights.",
    accommodation: "Amritsar luxury hotel partner list provided.",
    included: [
      "3 Days full access to Punjabi celebrations & grand banquets",
      "Bhangra dance workshop & headscarf for Gurdwara",
      "Cultural liaison support",
    ],
    notIncluded: ["Flight to Amritsar (ATQ)", "Hotel stay"],
    reviews: [],
    faqs: [],
  },
  {
    id: "curated-6",
    slug: "himalayan-heritage-destination-shimla",
    title: "Himalayan Heritage Destination Celebration",
    location: "Wildflower Hall, An Oberoi Resort, Shimla",
    city: "Shimla",
    state: "Himachal Pradesh",
    country: "India",
    countryCode: "IN",
    category: "Destination",
    pricePerGuest: 520,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    guestsAllowed: 20,
    guestsBooked: 0,
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=85",
    coupleImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&q=85",
    coupleName: "Kabir & Shreya Anand",
    hostName: "Anand Family of Shimla",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85",
    featured: true,
    tags: ["Himalayas", "Mountain View", "Pine Forest", "Bonfire Evening", "Colonial Luxury"],
    date: "2026-12-15",
    religion: "Hindu (Himachali Tradition)",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 2,
    languages: ["English", "Hindi", "Pahari"],
    isVerified: true,
    isCurated: true,
    curatedBadge: "Verified Showcase",
    gallery: [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=85",
      "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=85",
    ],
    story:
      "Exchange vows in the fresh mountain air of the Himalayas at 8,000 feet elevation. Surround yourself with pine forests, snow-capped mountain views, cozy evening bonfires, Himachali Dham feasts, and colonial luxury.",
    coupleBio:
      "Kabir is a mountain expedition guide and Shreya is an environmental lawyer. They invite international travelers to witness mountain wedding hospitality.",
    timeline: [
      {
        title: "Day 1: Pine Forest Bonfire & Himachali Dham",
        time: "16:00 - 21:30",
        date: "2026-12-15",
        description: "Evening acoustic bonfire under the stars, Pahari folk songs, mulled wine, and traditional Dham feast.",
        icon: "Flame",
      },
      {
        title: "Day 2: Mountain Peak Mandap & Afternoon Lawn Reception",
        time: "10:30 - 17:00",
        date: "2026-12-16",
        description: "Panoramic Himalayan peak wedding vows followed by gourmet mountain lawn buffet.",
        icon: "Compass",
      },
    ],
    traditions: [
      {
        title: "Himachali Nati Folk Dance",
        description: "Guinness World Record holding circular mountain folk dance.",
      },
      {
        title: "Traditional Dham Feast",
        description: "Festive meal cooked in brass vessels without onion or garlic by traditional Botis.",
      },
    ],
    dressCode: "Day 1: Warm Chic / Kashmiri Shawl; Day 2: Formal Mountain Suit or Velvet Silk Sari.",
    foodDescription: "Traditional Himachali Dham: Madra, Sepu Badi, Khatta, Meetha Bhat, and warm cardamom halwa.",
    venueDescription: "Outdoor cedar lawn at 8,250 feet with 360-degree views of the Greater Himalayas.",
    accommodation: "Oberoi Wildflower Hall mountain suite booking assistance provided upon reservation.",
    included: [
      "2 Days event access & mountain banquets",
      "Pahari shawl welcome gift",
      "Concierge liaison & mountain photowalk guide",
    ],
    notIncluded: ["Flight / Train to Shimla / Chandigarh", "Hotel stay"],
    reviews: [],
    faqs: [],
  },
];

export const weddingCategories: Category[] = [
  {
    id: "c1",
    name: "Royal",
    description: "Palace ceremonies with regal grandeur",
    imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=600&q=85",
    weddingCount: 2,
    icon: "Crown",
  },
  {
    id: "c2",
    name: "Punjabi",
    description: "Vibrant celebrations full of joy & bhangra",
    imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=600&q=85",
    weddingCount: 1,
    icon: "Sparkles",
  },
  {
    id: "c3",
    name: "South Indian",
    description: "Sacred traditions with temple elegance",
    imageUrl: "https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=600&q=85",
    weddingCount: 1,
    icon: "Flower2",
  },
  {
    id: "c4",
    name: "Beach",
    description: "Ocean-side romance at sunset",
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&q=85",
    weddingCount: 1,
    icon: "Waves",
  },
  {
    id: "c5",
    name: "Destination",
    description: "Exotic locales for unforgettable vows",
    imageUrl: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=600&q=85",
    weddingCount: 1,
    icon: "Compass",
  },
  {
    id: "c6",
    name: "Traditional",
    description: "Time-honoured rituals, timeless memories",
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=85",
    weddingCount: 1,
    icon: "Flame",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Eleanor & Mark Sterling",
    role: "Guests from London, UK",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=85",
    content:
      "Attending the Royal Udaipur celebration was the most moving cultural journey of our lives. The family welcomed us with open arms.",
    rating: 5,
    location: "London, UK",
    weddingType: "Royal Palace Wedding",
    date: "November 2025",
  },
  {
    id: "t2",
    name: "Jean-Pierre & Sophie Laurent",
    role: "Guests from Paris, France",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85",
    content:
      "From the sunset haldi to the oceanfront feast, every moment felt incredibly elegant. We created memories that will stay with us forever.",
    rating: 5,
    location: "Paris, France",
    weddingType: "Goa Beachfront Celebration",
    date: "December 2025",
  },
];

export const countries: Country[] = [
  {
    code: "IN",
    name: "India",
    weddingCount: 6,
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=85",
    description: "Rajasthan, Goa, Kerala, Punjab & more",
  },
  {
    code: "NP",
    name: "Nepal",
    weddingCount: 0,
    imageUrl: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=600&q=85",
    description: "Himalayan backdrops, ancient temples",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    weddingCount: 0,
    imageUrl: "https://images.unsplash.com/photo-1562602833-0f4ab2fc46e3?w=600&q=85",
    description: "Colonial heritage, tropical beaches",
  },
  {
    code: "TH",
    name: "Thailand",
    weddingCount: 0,
    imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&q=85",
    description: "Buddhist ceremonies, island escapes",
  },
];

export const faqItems: FAQItem[] = [
  {
    id: "f1",
    question: "How does Wedding With India work?",
    answer:
      "We connect discerning global travelers with trusted Host Families. Join real celebrations and experience timeless traditions as an honored member of the family.",
    category: "General",
  },
  {
    id: "f2",
    question: "Are these real weddings or arranged experiences?",
    answer:
      "Every celebration is entirely genuine. We personally verify each Host Family to ensure authenticity, safety, and welcoming hospitality.",
    category: "General",
  },
  {
    id: "f3",
    question: "What does the reservation include?",
    answer:
      "Your invitation provides full access to all rituals, traditional feasts, ceremonial welcome gifts, and a dedicated cultural liaison throughout the celebration.",
    category: "Pricing",
  },
  {
    id: "f4",
    question: "Is it respectful to attend someone's wedding?",
    answer:
      "Yes. Following the Indian tradition of 'Atithi Devo Bhava' (Guest is God), host families warmly welcome international guests to share their culture and joy.",
    category: "Safety",
  },
  {
    id: "f5",
    question: "What should I wear?",
    answer:
      "We encourage elegant traditional attire like silk sarees or bandhgalas. Your cultural liaison will assist with custom fittings upon arrival.",
    category: "Culture",
  },
  {
    id: "f6",
    question: "What is your cancellation policy?",
    answer:
      "We offer full refunds for cancellations made 30 days prior to the celebration. Detailed terms are available on our policies page.",
    category: "Booking",
  },
];

import { BUSINESS_METRICS } from "./constants/business-metrics";

export const heroStats: Stat[] = [
  {
    value: "100%",
    label: "Trusted Host Families",
    description: "Personally verified for authenticity",
  },
  {
    value: String(BUSINESS_METRICS.WEDDINGS_HOSTED_NUM),
    label: "Curated Celebrations",
    description: "Handpicked cultural journeys",
  },
  {
    value: String(BUSINESS_METRICS.AVERAGE_RATING_NUM) + " ★",
    label: "Wedding Host Families",
    description: "World-class warmth and care",
  },
];

export const howItWorksSteps: HowItWorksStep[] = [
  {
    step: 1,
    icon: "Search",
    title: "Discover",
    description:
      "Explore Our Indian Weddings across diverse regions. Each celebration is chosen for its authentic cultural heritage.",
  },
  {
    step: 2,
    icon: "ClipboardList",
    title: "Reserve Your Seat",
    description:
      "Request an invitation to join the family. Connect with a personal cultural guide for your journey.",
  },
  {
    step: 3,
    icon: "Plane",
    title: "Arrive as Family",
    description:
      "Your dedicated concierge greets you upon arrival, ensuring your absolute comfort throughout the festivities.",
  },
  {
    step: 4,
    icon: "Sparkles",
    title: "Celebrate Together",
    description:
      "Share in sacred rituals, timeless traditions, and genuine warmth. Create memories that last forever.",
  },
];
