import type {
  Wedding,
  Category,
  Testimonial,
  Country,
  FAQItem,
  Stat,
  HowItWorksStep,
} from "@/types";

export const featuredWeddings: Wedding[] = [
  {
    id: "demo-w1-rajasthan-5d",
    slug: "rajasthan-royal-family-celebration",
    title: "Rajasthan Royal Heritage Celebration",
    location: "Heritage Palace Estate, Jodhpur, Rajasthan",
    city: "Jodhpur",
    state: "Rajasthan",
    country: "India",
    countryCode: "IN",
    category: "Royal",
    tier: "SIGNATURE_ROYAL",
    pricePerGuest: 1199, // Signature Royal 5-day: $1,199 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 20,
    guestsBooked: 0,
    ceremoniesCount: 5,
    imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1615966650071-855b15f29ad1?w=400&q=80",
    coupleName: "Devika & Kaber Singhania",
    hostName: "Singhania Family",
    hostAvatar: "https://images.unsplash.com/photo-1615966650071-855b15f29ad1?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["5 Days", "Heritage Palace", "Folk Music", "Procession", "Royal Banquet"],
    date: "2026-11-18",
    religion: "Hindu",
    region: "Rajasthan",
    community: "Rajput Heritage",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 5,
    languages: ["English", "Hindi", "Rajasthani"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1200&q=80",
      "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1200&q=80",
      "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=1200&q=80",
    ],
    story: "Spend five days alongside a family celebration in Jodhpur, with opportunities to experience welcome gatherings, traditional folk performances, and the wedding ceremony in a heritage palace setting.",
    coupleBio: "The Singhania family welcomes international guests to experience authentic Marwari hospitality and cultural traditions.",
    timeline: [
      { date: "Day 1", time: "16:00 - 21:00", title: "Day 1: Family Welcome & Evening Gathering", description: "Arrival of guests, welcome tea, traditional folk musicians, and courtyard dinner.", icon: "Sparkles" },
      { date: "Day 2", time: "11:00 - 15:00", title: "Day 2: Pre-Wedding Family Celebrations", description: "Daytime cultural activities, floral decorations, and regional culinary stalls.", icon: "Sparkles" },
      { date: "Day 3", time: "18:00 - 23:00", title: "Day 3: Musical Evening & Sangeet", description: "Choreographed family dances, live folk orchestra, and evening banquet.", icon: "Music" },
      { date: "Day 4", time: "16:30 - 22:00", title: "Day 4: Traditional Procession & Wedding Ceremony", description: "Baraat assembly, sacred vows around the holy fire with English cultural commentary, and dinner.", icon: "HeartHandshake" },
      { date: "Day 5", time: "19:00 - 23:30", title: "Day 5: Royal Gala Reception & Farewell", description: "Congratulatory dinner, toasts, fireworks, and farewell blessing.", icon: "PartyPopper" },
    ],
    traditions: [
      { title: "Baraat Procession", description: "Groom's festive arrival accompanied by musicians and dancing family members." },
      { title: "Saptapadi Vows", description: "Seven sacred vows taken together around the holy Agni fire." },
    ],
    dressCode: "Festive Indian Ethnic (Sherwani, Kurta, Lehenga, Saree) or Black Tie Formal",
    foodDescription: "Royal Marwari vegetarian feast with live dessert stations and regional delicacies.",
    venueDescription: "Heritage Palace Estate courtyard and gardens in Jodhpur.",
    accommodation: "Heritage Palace Pavilion Suites.",
    included: ["All-day access to scheduled events", "Authentic wedding feasts and refreshments", "Dedicated guest liaison support"],
    notIncluded: ["International flights", "Personal travel insurance"],
    reviews: [],
    faqs: [],
    guestRules: "Guests may observe sacred rituals and join the family celebration during evening music and reception.",
    etiquetteNotes: "Footwear is removed before entering sacred ceremonial pavilions. Turbans provided for male guests.",
  },
  {
    id: "demo-w2-kerala-3d",
    slug: "kerala-coastal-christian-celebration",
    title: "Kerala Coastal Christian Matrimony",
    location: "Waterfront Coconut Grove Estate, Alleppey, Kerala",
    city: "Alleppey",
    state: "Kerala",
    country: "India",
    countryCode: "IN",
    category: "Nature",
    tier: "GRAND",
    pricePerGuest: 449, // Grand 3-day: $449 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 12,
    guestsBooked: 0,
    ceremoniesCount: 3,
    imageUrl: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coupleName: "Mathew & Teresa Kurian",
    hostName: "Kurian Family",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["3 Days", "Backwaters", "Church Matrimony", "Sadya Feast", "Sunset Cruise"],
    date: "2027-01-14",
    religion: "Christian",
    region: "Kerala",
    community: "Saint Thomas Christian",
    luxuryLevel: "Luxury",
    durationDays: 3,
    languages: ["English", "Malayalam"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=1200&q=80",
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    ],
    story: "Experience three days of serene coastal hospitality in Alleppey, featuring a sunset backwater gathering, a solemn church matrimony mass, and an authentic banana leaf Sadya feast.",
    coupleBio: "Mathew & Teresa welcome cultural travelers to share in coastal Kerala warmth and heritage.",
    timeline: [
      { date: "Day 1", time: "16:30 - 20:30", title: "Day 1: Sunset Backwater Gathering & Welcome", description: "Arrival boat cruise across backwater canals, fresh coconut drinks, and evening family dinner.", icon: "Sparkles" },
      { date: "Day 2", time: "10:30 - 15:00", title: "Day 2: Church Matrimony & Nuptial Blessing", description: "Solemn Catholic marriage mass in a heritage stone church followed by family congratulations.", icon: "HeartHandshake" },
      { date: "Day 3", time: "12:00 - 16:30", title: "Day 3: Traditional Ela Sadya Feast & Cultural Reception", description: "24-item vegetarian feast served on banana leaves with classical instrumental music.", icon: "Utensils" },
    ],
    traditions: [
      { title: "Nuptial Mass", description: "Solemn church matrimony with choir hymns and matrimonial vows." },
      { title: "Traditional Ela Sadya", description: "Multi-course feast served on fresh green banana leaves." },
    ],
    dressCode: "Kasavu Saree / Cream Mundu with Shirt or Smart Semi-Formal Linen",
    foodDescription: "Traditional Kerala feast served on banana leaves alongside fresh coastal specialties.",
    venueDescription: "Waterfront estate and heritage church in Alleppey.",
    accommodation: "Waterfront resort cottages.",
    included: ["Access to all three days of celebration", "Banana leaf Sadya and event dining", "Local transport coordination"],
    notIncluded: ["International airfare", "Alcoholic beverages during church service"],
    reviews: [],
    faqs: [],
    guestRules: "Guests attend the church ceremony as respectful observers and actively join the reception and feast.",
    etiquetteNotes: "Please maintain quiet reverence inside the church. Sadya is traditionally enjoyed with the right hand.",
  },
  {
    id: "demo-w3-punjab-4d",
    slug: "punjabi-sikh-anand-karaj-experience",
    title: "Punjabi Sikh Wedding Experience",
    location: "Heritage Farmstead & Gurdwara, Amritsar, Punjab",
    city: "Amritsar",
    state: "Punjab",
    country: "India",
    countryCode: "IN",
    category: "Traditional",
    tier: "ROYAL",
    pricePerGuest: 799, // Royal 4-day: $799 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 16,
    guestsBooked: 0,
    ceremoniesCount: 4,
    imageUrl: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&q=80",
    coupleName: "Gurpreet & Harleen Dhillon",
    hostName: "Dhillon Family",
    hostAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["4 Days", "Anand Karaj", "Dhol Drums", "Bhangra", "Gurdwara Langar"],
    date: "2027-04-12",
    religion: "Sikh",
    region: "Punjab",
    community: "Punjabi Sikh",
    luxuryLevel: "Luxury",
    durationDays: 4,
    languages: ["English", "Punjabi", "Hindi"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=1200&q=80",
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    ],
    story: "Four days of vibrant Punjabi warmth in Amritsar, featuring lively Dhol drumming, colorful family folk dances, the sacred Anand Karaj ceremony in a Gurdwara, and celebratory banquets.",
    coupleBio: "The Dhillon family invites global travelers to experience true Punjabi hospitality, sacred music, and community spirit.",
    timeline: [
      { date: "Day 1", time: "17:00 - 22:00", title: "Day 1: Welcome Dinner & Village Gathering", description: "Farmstead welcome, traditional tandoori dinner, and folk storytelling.", icon: "Sparkles" },
      { date: "Day 2", time: "18:00 - 23:30", title: "Day 2: Sangeet & Folk Dance Night", description: "High-energy Dhol beats, family choreography, and traditional Punjabi buffet.", icon: "Music" },
      { date: "Day 3", time: "09:00 - 14:00", title: "Day 3: Sacred Anand Karaj & Community Langar", description: "Solemn four Laavan hymns in the Gurdwara followed by equality community meal (Langar).", icon: "HeartHandshake" },
      { date: "Day 4", time: "19:00 - 23:45", title: "Day 4: Grand Wedding Reception & Dinner", description: "Celebratory reception banquet, DJ entertainment, congratulatory toasts, and fireworks.", icon: "PartyPopper" },
    ],
    traditions: [
      { title: "Laavan (Anand Karaj)", description: "Four sacred circumambulations around Sri Guru Granth Sahib Ji binding the couple spiritually." },
      { title: "Guru Ka Langar", description: "Traditional community meal served with humility and equality to all guests." },
    ],
    dressCode: "Bright Punjabi Kurta Pajama / Turban for men; Salwar Kameez / Lehenga for women",
    foodDescription: "Rich Punjabi cuisine: Dal Makhani, Amritsari Kulcha, Paneer Tikka, and Kadah Prasad.",
    venueDescription: "Heritage agricultural estate and local Gurdwara in Amritsar.",
    accommodation: "Heritage farmstay luxury suites.",
    included: ["Full 4-day celebration access", "Head coverings and scarves for Gurdwara", "Feasts and transport between venues"],
    notIncluded: ["Flights to Amritsar"],
    reviews: [],
    faqs: [],
    guestRules: "Head covering and shoe removal are mandatory inside the Gurdwara. Guests are honored observers during Laavan.",
    etiquetteNotes: "Tobacco and alcohol are strictly prohibited on Gurdwara grounds. Head coverings (Rumaal) provided on arrival.",
  },
  {
    id: "demo-w4-goa-2d",
    slug: "goa-coastal-family-wedding",
    title: "Goa Coastal Family Celebration",
    location: "Seaside Garden & Heritage Villa, Mandrem, Goa",
    city: "Mandrem",
    state: "Goa",
    country: "India",
    countryCode: "IN",
    category: "Beach",
    tier: "ENHANCED",
    pricePerGuest: 249, // Enhanced 2-day: $249 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 10,
    guestsBooked: 0,
    ceremoniesCount: 2,
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    coupleName: "Zaid & Nusrat Khan",
    hostName: "Khan Family",
    hostAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["2 Days", "Beachfront", "Nikah Ceremony", "Walima Feast", "Coastal Music"],
    date: "2027-02-12",
    religion: "Muslim",
    region: "Goa",
    community: "Konkani Muslim",
    luxuryLevel: "Luxury",
    durationDays: 2,
    languages: ["English", "Konkani", "Hindi", "Urdu"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    ],
    story: "A warm two-day celebration in coastal North Goa, featuring sunset welcome refreshments, a traditional Nikah matrimony, and an oceanfront Walima dinner reception.",
    coupleBio: "Zaid & Nusrat celebrate coastal Goan heritage and invite travelers to experience sincere family hospitality.",
    timeline: [
      { date: "Day 1", time: "17:00 - 21:30", title: "Day 1: Sunset Welcome Gathering & Tea", description: "Coastal tea reception, acoustic Sufi melodies, and beachfront dinner.", icon: "Sparkles" },
      { date: "Day 2", time: "16:00 - 23:00", title: "Day 2: Nikah Matrimony & Walima Banquet", description: "Solemn Nikah blessing followed by seaside celebratory Walima dinner with fresh coastal delicacies.", icon: "HeartHandshake" },
    ],
    traditions: [
      { title: "Nikah Ceremony", description: "Formal Islamic marriage contract officiated in the presence of family witnesses." },
      { title: "Walima Feast", description: "Joyful celebratory dinner hosted by the groom's family to share the blessing with guests." },
    ],
    dressCode: "Smart Coastal Formal / Modest Festive Wear (Sherwani, Kurta, Sharara, or Linen Suit)",
    foodDescription: "Coastal biryanis, fresh grilled seafood, Goan vegetarian curries, and traditional sweets.",
    venueDescription: "Seaside garden villa overlooking Mandrem Beach.",
    accommodation: "Boutique coastal villas.",
    included: ["Access to both days of celebration", "Gourmet coastal feasts and refreshments"],
    notIncluded: ["Flights to Goa"],
    reviews: [],
    faqs: [],
    guestRules: "Guests observe the Nikah ceremony respectfully and join the family for dinner and congratulations.",
    etiquetteNotes: "Modest, smart attire is appreciated during the ceremonial signing.",
  },
  {
    id: "demo-w5-gujarat-2d",
    slug: "gujarat-jain-family-matrimony",
    title: "Gujarat Heritage Family Celebration",
    location: "Heritage Haveli Courtyard, Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    countryCode: "IN",
    category: "Traditional",
    tier: "STANDARD",
    pricePerGuest: 189, // Standard 2-day: $189 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 8,
    guestsBooked: 0,
    ceremoniesCount: 2,
    imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
    coupleImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coupleName: "Chirag & Mansi Shah",
    hostName: "Shah Family",
    hostAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["2 Days", "Heritage Haveli", "Jain Sattvic Feast", "Garba Music", "Sacred Vows"],
    date: "2027-03-20",
    religion: "Jain",
    region: "Gujarat",
    community: "Jain Shwetambar",
    luxuryLevel: "Premium",
    durationDays: 2,
    languages: ["English", "Gujarati", "Hindi"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    ],
    story: "Two days of time-honoured traditions in Ahmedabad, including an evening of gentle traditional Garba folk music and a sacred morning wedding ceremony followed by pure Sattvic dining.",
    coupleBio: "The Shah family welcomes guests to experience peaceful Jain traditions and Ahmedabad's living architectural heritage.",
    timeline: [
      { date: "Day 1", time: "18:00 - 22:30", title: "Day 1: Cultural Welcome & Traditional Garba Evening", description: "Haveli courtyard welcome, gentle traditional Raas Garba dance, and vegetarian dinner.", icon: "Music" },
      { date: "Day 2", time: "09:30 - 14:30", title: "Day 2: Sacred Marriage Ceremony & Sattvic Feast", description: "Morning marriage rituals, Mangalphera blessings, and royal pure vegetarian Gujarati banquet.", icon: "HeartHandshake" },
    ],
    traditions: [
      { title: "Mangalphera Blessings", description: "Four sacred rounds representing Dharma, Artha, Kama, and Moksha." },
      { title: "Pure Sattvic Dining", description: "Ethically prepared vegetarian banquet without root vegetables or artificial additives." },
    ],
    dressCode: "Traditional Gujarati Ethnic (Bandhani / Patola Saree or Kurta Pajama)",
    foodDescription: "Pure Jain Sattvic multi-course feast prepared with traditional purity standards.",
    venueDescription: "Restored 18th-century heritage haveli in Ahmedabad.",
    accommodation: "Haveli guest suites.",
    included: ["Access to both celebration days", "Traditional pure vegetarian banquets"],
    notIncluded: ["Flights to Ahmedabad"],
    reviews: [],
    faqs: [],
    guestRules: "Strictly vegetarian and alcohol-free celebration. Guests are welcomed as honored observers.",
    etiquetteNotes: "Please remove shoes before entering the ceremony mandap area.",
  },
  {
    id: "demo-w6-delhi-4d",
    slug: "delhi-interfaith-multicultural-celebration",
    title: "Interfaith Celebration in Delhi",
    location: "Garden Pavilion & Heritage Estate, New Delhi",
    city: "New Delhi",
    state: "Delhi",
    country: "India",
    countryCode: "IN",
    category: "Destination",
    tier: "ROYAL",
    pricePerGuest: 799, // Royal 4-day: $799 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 16,
    guestsBooked: 0,
    ceremoniesCount: 4,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    coupleImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    coupleName: "Rahul & Sophie Deshmukh",
    hostName: "Deshmukh & Laurent Families",
    hostAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["4 Days", "Interfaith", "Garden Estate", "Fusion Banquet", "Multicultural"],
    date: "2027-05-15",
    religion: "Interfaith / Multicultural",
    region: "Delhi",
    community: "Multicultural Union",
    luxuryLevel: "Ultra-Luxury",
    durationDays: 4,
    languages: ["English", "Hindi", "French"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=1200&q=80",
    ],
    story: "A thoughtful four-day interfaith wedding in New Delhi bringing together Indian and European traditions, featuring a welcome mixer, musical night, personalized ceremony, and grand gala.",
    coupleBio: "Rahul & Sophie invite international travelers to witness a celebration that bridges cultures, languages, and families.",
    timeline: [
      { date: "Day 1", time: "18:00 - 22:00", title: "Day 1: Welcome Mixer & Cocktail Evening", description: "Garden estate gathering with fusion hors d'oeuvres and family welcome toasts.", icon: "Sparkles" },
      { date: "Day 2", time: "18:30 - 23:30", title: "Day 2: Musical Night & Cultural Performances", description: "Interactive dance lessons, live acoustic performances, and gourmet dinner.", icon: "Music" },
      { date: "Day 3", time: "16:00 - 21:00", title: "Day 3: Multicultural Wedding Ceremony", description: "Personalized dual-tradition vows celebrating shared heritage, exchange of rings and garlands.", icon: "HeartHandshake" },
      { date: "Day 4", time: "19:00 - 00:00", title: "Day 4: Gala Reception & Celebration Party", description: "Grand candlelit dinner, wedding cake cutting, speeches, and dancing.", icon: "PartyPopper" },
    ],
    traditions: [
      { title: "Garland & Ring Exchange", description: "Harmonious union combining Indian Jaimala garland exchange and western wedding rings." },
      { title: "Interfaith Blessing", description: "Inspirational readings and blessings honoring both families' roots." },
    ],
    dressCode: "Festive Indian Ethnic or Western Black Tie Formal",
    foodDescription: "Curated Indian and global gastronomy crafted by master chefs.",
    venueDescription: "Lush private garden estate on the outskirts of New Delhi.",
    accommodation: "Estate luxury guest villas.",
    included: ["All 4-day event access", "Gourmet dining and beverages", "Liaison coordination"],
    notIncluded: ["Flights to Delhi"],
    reviews: [],
    faqs: [],
    guestRules: "Open participation throughout the celebration.",
    etiquetteNotes: "Dress elegantly for evening events.",
  },
  {
    id: "demo-w7-tamil-1d",
    slug: "chennai-coastal-temple-wedding",
    title: "Chennai Coastal Cultural Celebration",
    location: "Seaside Heritage Mandapam, Mahabalipuram, Tamil Nadu",
    city: "Mahabalipuram",
    state: "Tamil Nadu",
    country: "India",
    countryCode: "IN",
    category: "Traditional",
    tier: "STANDARD",
    pricePerGuest: 149, // Standard 1-day: $149 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 8,
    guestsBooked: 0,
    ceremoniesCount: 1,
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&q=80",
    coupleImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coupleName: "Karthik & Deepa Ramanathan",
    hostName: "Ramanathan Family",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    featured: true,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["1 Day", "Coastal Tamil", "Nadaswaram", "Ela Sadya", "Temple Style"],
    date: "2027-06-11",
    religion: "Hindu",
    region: "Tamil Nadu",
    community: "Tamil Traditional",
    luxuryLevel: "Premium",
    durationDays: 1,
    languages: ["English", "Tamil"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&q=80",
    ],
    story: "A focused one-day cultural celebration by the Bay of Bengal in Mahabalipuram, featuring morning Nadaswaram recitals, Mangalya Dharanam blessings, and a traditional banana leaf feast.",
    coupleBio: "The Ramanathan family welcomes visitors to experience pure South Indian classical wedding traditions.",
    timeline: [
      { date: "Day 1", time: "08:30 - 14:00", title: "Day 1: Morning Sacred Matrimony & Traditional Feast", description: "Classical Nadaswaram music, Oonjal swing ceremony, Mangalya Dharanam, and grand Ela Sadya.", icon: "Sparkles" },
    ],
    traditions: [
      { title: "Mangalya Dharanam", description: "Sacred tying of the gold Mangalsutra thread." },
      { title: "Oonjal Swing Ritual", description: "Couple seated on an ornate swing while women sing traditional blessing songs." },
    ],
    dressCode: "Traditional South Indian Veshti / Kanchipuram Silk Saree or Smart Modest Attire",
    foodDescription: "Pure vegetarian Tamil banana leaf Sadya feast with filter coffee.",
    venueDescription: "Heritage seaside mandapam in Mahabalipuram.",
    accommodation: "Coastal resort suites.",
    included: ["Full 1-day wedding entry", "Authentic banana leaf feast"],
    notIncluded: ["Flights to Chennai"],
    reviews: [],
    faqs: [],
    guestRules: "Guests observe sacred rites and enjoy the seated banana leaf feast.",
    etiquetteNotes: "Please remove footwear before entering the ceremonial hall.",
  },
  {
    id: "demo-w8-himachal-3d",
    slug: "shimla-himalayan-meadow-celebration",
    title: "Himachal Mountain Meadow Union",
    location: "Cedar Valley Estate, Shimla, Himachal Pradesh",
    city: "Shimla",
    state: "Himachal Pradesh",
    country: "India",
    countryCode: "IN",
    category: "Nature",
    tier: "GRAND",
    pricePerGuest: 449, // Grand 3-day: $449 USD
    currency: "USD",
    rating: 0,
    reviewCount: 0,
    guestsAllowed: 14,
    guestsBooked: 0,
    ceremoniesCount: 3,
    imageUrl: "https://images.unsplash.com/photo-1640953148126-1962ec17a92b?q=80&w=1170&auto=format&fit=crop",
    coupleImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coupleName: "Vikram & Sunaina Thakur",
    hostName: "Thakur Family",
    hostAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    featured: false,
    sponsored: false,
    isDemo: true,
    availabilityStatus: "FULLY_BOOKED",
    tags: ["3 Days", "Himalayan Ridge", "Pahari Dham", "Cedar Forest", "Mountain Views"],
    date: "2027-07-08",
    religion: "Regional / Cultural",
    region: "Himachal Pradesh",
    community: "Pahadi Heritage",
    luxuryLevel: "Luxury",
    durationDays: 3,
    languages: ["English", "Hindi", "Pahadi"],
    isVerified: false,
    isCurated: true,
    curatedBadge: "Featured",
    gallery: [
      "https://images.unsplash.com/photo-1640953148126-1962ec17a92b?q=80&w=1170&auto=format&fit=crop",
    ],
    story: "Three days amidst cedar forests in Shimla, featuring mountain folk songs, a meadow ceremony overlooking Himalayan ridges, and an authentic Himachali Dham feast.",
    coupleBio: "The Thakur family invites guests to share the serenity and traditions of mountain life.",
    timeline: [
      { date: "Day 1", time: "16:00 - 21:00", title: "Day 1: Alpine Welcome & Bonfire Gathering", description: "Himalayan herbal tea welcome, acoustic folk music, and bonfire dinner.", icon: "Sparkles" },
      { date: "Day 2", time: "11:00 - 15:30", title: "Day 2: Mountain Meadow Wedding & Sacred Vows", description: "Traditional wedding ceremony amidst pine trees followed by the auspicious Dham feast.", icon: "HeartHandshake" },
      { date: "Day 3", time: "12:00 - 16:00", title: "Day 3: Farewell Brunch & Ridge Walk", description: "Informal brunch with mountain views and family blessings.", icon: "PartyPopper" },
    ],
    traditions: [
      { title: "Himachali Dham", description: "Celebratory multi-course meal prepared by traditional master cooks (Botis)." },
      { title: "Pahadi Nati Dance", description: "Gentle rhythmic community circle dance celebrating togetherness." },
    ],
    dressCode: "Warm Festive Attire / Velvet Ethnic / Woolen Shawls",
    foodDescription: "Traditional Himachali Dham cooked in brass pots with mountain herbs.",
    venueDescription: "Cedar valley estate in Shimla.",
    accommodation: "Himalayan mountain resort.",
    included: ["All 3-day events", "Dham feasts and beverages"],
    notIncluded: ["Flights to Chandigarh/Shimla"],
    reviews: [],
    faqs: [],
    guestRules: "Comfortable footwear recommended for mountain paths.",
    etiquetteNotes: "Please bring warm layers for cooler mountain evenings.",
  },
];

export const categories: Category[] = [
  {
    id: "royal",
    name: "Royal",
    slug: "royal",
    count: 6,
    weddingCount: 6,
    icon: "Crown",
    description: "Grand palaces, regal traditions & Maharaja heritage",
    imageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80",
  },
  {
    id: "punjabi",
    name: "Punjabi",
    slug: "punjabi",
    count: 3,
    weddingCount: 3,
    icon: "Flame",
    description: "Vibrant celebrations full of joy, dhol & bhangra",
    imageUrl: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?w=800&q=80",
  },
  {
    id: "south-indian",
    name: "South Indian",
    slug: "south-indian",
    count: 4,
    weddingCount: 4,
    icon: "Flower2",
    description: "Sacred traditions with temple elegance & banana leaf sadyas",
    imageUrl: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
  },
  {
    id: "beach",
    name: "Beach",
    slug: "beach",
    count: 3,
    weddingCount: 3,
    icon: "Waves",
    description: "Ocean-side romance at sunset along coastal shores",
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
  },
  {
    id: "destination",
    name: "Destination",
    slug: "destination",
    count: 4,
    weddingCount: 4,
    icon: "Compass",
    description: "Exotic locales from Himalayan peaks to tea estates",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
  },
  {
    id: "traditional",
    name: "Traditional",
    slug: "traditional",
    count: 5,
    weddingCount: 5,
    icon: "Sparkles",
    description: "Time-honoured rituals, spiritual unions & rich heritage",
    imageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&q=80",
  },
  {
    id: "nature",
    name: "Nature",
    slug: "nature",
    count: 3,
    weddingCount: 3,
    icon: "Trees",
    description: "Backwater groves, mountain meadows & pine valleys",
    imageUrl: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&q=80",
  },
];

export const weddingCategories = categories;

export const stats: Stat[] = [
  { label: "Curated Celebrations", value: "Multi-Day" },
  { label: "Partner Regions", value: "12+" },
  { label: "Cultural Traditions", value: "Diverse" },
];

export const heroStats = stats;

export const testimonials: Testimonial[] = [];

export const countries: Country[] = [
  {
    code: "RJ",
    name: "Rajasthan",
    weddingCount: 5,
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&q=80",
    description: "Palaces, golden dunes, and grand haveli celebrations in Jodhpur, Jaipur & Udaipur.",
  },
  {
    code: "GA",
    name: "Goa",
    weddingCount: 3,
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    description: "Coastal celebrations, oceanfront mandaps, and tropical sunset receptions.",
  },
  {
    code: "KL",
    name: "Kerala",
    weddingCount: 3,
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    description: "Serene backwater houseboats, banana leaf Sadya feasts, and palm-shaded rituals.",
  },
  {
    code: "PB",
    name: "Punjab",
    weddingCount: 2,
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    description: "Vibrant Anand Karaj ceremonies, Golden Temple heritage, and high-energy Dhol bhangra.",
  },
  {
    code: "DL",
    name: "Delhi & North",
    weddingCount: 3,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    description: "Sprawling garden estates, multicultural unions, and imperial heritage banquets.",
  },
  {
    code: "SI",
    name: "South India & Hills",
    weddingCount: 4,
    imageUrl: "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&q=80",
    description: "Coastal temple mandapams, Himalayan pine valleys, and classical music ceremonies.",
  },
];

export const faqItems: FAQItem[] = [
  {
    id: "f1",
    question: "What is WeddingWithIndia?",
    answer: "WeddingWithIndia is a premier cultural platform connecting international travelers and cultural enthusiasts with real Indian families hosting authentic wedding celebrations across India.",
    category: "General",
  },
  {
    id: "f2",
    question: "How are hosts and weddings verified?",
    answer: "Every wedding host undergoes strict identity verification, profile screening, and ceremony schedule review by our admin team before listing their celebration.",
    category: "Verification",
  },
  {
    id: "f3",
    question: "What is included with a Guest Pass?",
    answer: "A Guest Pass includes access to scheduled ceremonial events, authentic wedding feasts, cultural performances, and assigned wedding buddy support.",
    category: "Experience",
  },
  {
    id: "f4",
    question: "What traditions and celebration durations are available?",
    answer: "WeddingWithIndia offers 1-day, 2-day, 3-day, 4-day, and 5-day wedding experiences across diverse traditions including Hindu, Muslim, Sikh, Christian, Jain, Buddhist, and Interfaith celebrations.",
    category: "Experience",
  },
];

export const howItWorksSteps: HowItWorksStep[] = [
  {
    step: 1,
    icon: "Compass",
    title: "Browse Curated Celebrations",
    description: "Explore 1-day to 5-day authentic wedding experiences across Rajasthan, Kerala, Punjab, and Goa.",
  },
  {
    step: 2,
    icon: "UserCheck",
    title: "Request Host Approval",
    description: "Submit your guest profile for host review and receive personalized event details upon verification.",
  },
  {
    step: 3,
    icon: "PlaneTakeoff",
    title: "Prepare & Travel Support",
    description: "Your dedicated guest liaison assists with airport pickup, hotel coordination, and traditional attire guidance.",
  },
  {
    step: 4,
    icon: "Sparkles",
    title: "Attend as an Honoured Guest",
    description: "Receive your digital VIP Guest Pass, step inside sacred rituals, feast, dance, and celebrate as family.",
  },
];
