import { requireRole } from "@/lib/auth";
import { UserRole } from "@prisma/client";
import { getGrowthDashboardAction } from "@/lib/actions/admin-dashboards";
import { TrendingUp, Users, Ticket, Tag } from "lucide-react";
import { formatDate } from "@/lib/utils";


export const dynamic = "force-dynamic";

export default async function ExecutiveGrowthDashboardPage() {
  await requireRole([UserRole.ADMIN]);
  const growth = await getGrowthDashboardAction();

  return (
    <div className="space-y-8 animate-fade-in">
      <div className="space-y-1">
        <h1 className="font-display font-bold text-2xl sm:text-3xl text-charcoal-900 flex items-center gap-2">
          <TrendingUp className="text-emerald-600 w-8 h-8" />
          Executive Growth & Marketing Dashboard
        </h1>
        <p className="text-charcoal-500 text-xs sm:text-sm">
          Acquisition metrics, newsletter subscriber performance, travel agent referrals, and promo coupon analytics.
        </p>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="bg-white border border-warm-200/60 p-6 rounded-[2rem] shadow-sm space-y-2">
          <div className="flex items-center justify-between text-emerald-600">
            <span className="text-[0.6875rem] font-bold uppercase tracking-wider text-charcoal-500">Newsletter Subscribers</span>
            <Users size={18} />
          </div>
          <div className="font-display font-bold text-2xl text-charcoal-900">
            {growth.subscribersCount}
          </div>
          <p className="text-[0.6875rem] text-charcoal-400">Total email leads captured.</p>
        </div>

        <div className="bg-white border border-warm-200/60 p-6 rounded-[2rem] shadow-sm space-y-2">
          <div className="flex items-center justify-between text-amber-600">
            <span className="text-[0.6875rem] font-bold uppercase tracking-wider text-charcoal-500">Agent Referrals</span>
            <Ticket size={18} />
          </div>
          <div className="font-display font-bold text-2xl text-amber-700">
            {growth.referralsCount}
          </div>
          <p className="text-[0.6875rem] text-charcoal-400">Referrals generated by travel agents.</p>
        </div>

        <div className="bg-white border border-warm-200/60 p-6 rounded-[2rem] shadow-sm space-y-2">
          <div className="flex items-center justify-between text-maroon-600">
            <span className="text-[0.6875rem] font-bold uppercase tracking-wider text-charcoal-500">Active Promo Coupons</span>
            <Tag size={18} />
          </div>
          <div className="font-display font-bold text-2xl text-maroon-700">
            {growth.activeCouponsCount}
          </div>
          <p className="text-[0.6875rem] text-charcoal-400">Promotional discount codes.</p>
        </div>
      </div>

      {/* Lists */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white border border-warm-200/60 p-6 sm:p-8 rounded-[2rem] shadow-sm space-y-4">
          <h3 className="font-display font-bold text-base text-charcoal-900 border-b border-warm-100 pb-3 flex items-center gap-2">
            <Users size={18} className="text-emerald-600" />
            Recent Newsletter Subscribers ({growth.newsletterSubscribers.length})
          </h3>
          {growth.newsletterSubscribers.length === 0 ? (
            <div className="p-8 text-center text-xs text-charcoal-400 font-semibold">No subscribers registered yet.</div>
          ) : (
            <div className="space-y-3 max-h-[400px] overflow-y-auto pr-1">
              {growth.newsletterSubscribers.map((s: any) => (
                <div key={s.id} className="p-3 bg-warm-50/50 border border-warm-200 rounded-2xl text-xs flex justify-between">
                  <span className="font-semibold text-charcoal-900">{s.email}</span>
                  <span className="text-[0.6875rem] text-charcoal-400">{formatDate(s.createdAt)}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="bg-white border border-warm-200/60 p-6 sm:p-8 rounded-[2rem] shadow-sm space-y-4">
          <h3 className="font-display font-bold text-base text-charcoal-900 border-b border-warm-100 pb-3 flex items-center gap-2">
            <Tag size={18} className="text-maroon-600" />
            Active Promo Coupons ({growth.coupons.length})
          </h3>
          {growth.coupons.length === 0 ? (
            <div className="p-8 text-center text-xs text-charcoal-400 font-semibold">No promo coupons configured yet. Manage via Founder Panel.</div>
          ) : (
            <div className="space-y-3 max-h-[400px] overflow-y-auto pr-1">
              {growth.coupons.map((c: any) => (
                <div key={c.id} className="p-3.5 bg-warm-50/50 border border-warm-200 rounded-2xl text-xs flex justify-between items-center">
                  <div>
                    <span className="font-bold text-maroon-700 block">{c.code}</span>
                    <span className="text-[0.6875rem] text-charcoal-500">{c.type === "PERCENTAGE" ? `${c.discountValue}% OFF` : `$${c.discountValue} OFF`}</span>
                  </div>
                  <span className="text-xs font-bold text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-200">Active</span>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
